### ISSUE TITLE
RSVP broken when no user logged in 

### ISSUE THREAD

**Issue by saulshanabrook** [paviliondev/discourse-events#114]
I notice that if no user is logged in and an event has an RSVP, the page will fail to fully load:

<img width="1410" alt="Screenshot 2023-02-19 at 12 57 14 PM" src="https://user-images.githubusercontent.com/1186124/219966124-046f37b9-a12c-4077-827a-e21ecdd6b049.png">

Once I turned RSVPs off for its event, it loads properly.

**Comment by angusmcleod** [comment]
@saulshanabrook Thanks, this is fixed in https://github.com/paviliondev/discourse-events/commit/f349713e8260b30c52a0e5c8106716d8b0c51c3d

**Comment by saulshanabrook** [comment]
@angusmcleod Thank you! ❤️
