### ISSUE TITLE
Allow user to update event details in title edit area.

### ISSUE THREAD

**Issue by angusmcleod** [paviliondev/discourse-events#31]
Currently the only way to edit the event details is in the composer. As events are 'topic' properties, according to the design logic of Discourse you should also be able to edit them in the title edit area (where you edit the topic title, category and tags). 

Broadly speaking, this is a matter of putting the ``add-event-controls`` component in the ``edit-topic`` plugin outlet. Start by just trying to just copy across the ``composer-fields/composer-controls-event.hbs`` template to the ``edit-topic`` outlet.

**Comment by fzngagan** [comment]
@angusmcleod  This is done, right?

**Comment by angusmcleod** [comment]
@fzngagan Yup :+1:
