### ISSUE TITLE
ics requires a parameter

### ISSUE THREAD

**Issue by niccokunzmann** [paviliondev/discourse-events#44]
I would like to use your software to display calendar events and subscribe to the ICS feed.

I tool an hour searching.

This is expected with a parameter.
https://forum.wilap.de/c/machbar/l/calendar.ics?time_zone=Europe/Berlin
Can we document this somewhere, so other do not need to look that far?
Good would also be not to report that below but to tell the user to add a parameter.
https://forum.wilap.de/c/machbar/l/calendar.ics
```
Oops

The software powering this discussion forum encountered an unexpected problem. We apologize for the inconvenience.

Detailed information about the error was logged, and an automatic notification generated. We'll take a look at it.

No further action is necessary. However, if the error condition persists, you can provide additional detail, including steps to reproduce the error, by posting a discussion topic in the site's feedback category.
```

I have been searching in many places. These did it for me:
- https://github.com/angusmcleod/discourse-events/blob/6570a75933b63fdb696cc079c9cd0aa0dcecdf8e/assets/javascripts/discourse/components/events-calendar-subscription.js.es6#L14
- https://github.com/angusmcleod/discourse-events/blob/8b356e3e36e88a141289d60ec4c63ba6620ca262/plugin.rb#L511

**Comment by niccokunzmann** [comment]
This place would need to change.
https://github.com/angusmcleod/discourse-events/blob/master/plugin.rb#L471
Options:
- We could use UTC as default time zone.
- We can create a meaningful error message.
What are your thoughts?

**Comment by fzngagan** [comment]
@niccokunzmann Yes we also came across this one recently. I'll take a look in a couple of days.

**Comment by niccokunzmann** [comment]
I think, in the settings, there is a default time zone for all events.
Maybe this one can be used as a default for the ICS export, too.

**Comment by fzngagan** [comment]
I've made a PR here: https://github.com/paviliondev/discourse-events/pull/68

**Comment by niccokunzmann** [comment]
This is not done, yet. From an implementation side, it is, see #68. However, this should be documented somewhere. Otherwise, it is not usable.

**Comment by fzngagan** [comment]
> This is not done, yet. From an implementation side, it is, see #68. However, this should be documented somewhere. Otherwise, it is not usable.

@niccokunzmann, Sure man We'll put that into the O/P on meta. Other than that, do you have any questions about the implementation?

**Comment by niccokunzmann** [comment]
No, seems fine to me! Thanks for taking care of that!
