### ISSUE TITLE
Feature Request: colour events with different colours

### ISSUE THREAD

**Issue by elRicharde** [paviliondev/discourse-events#53]
Would be nice to give different Events in one calender different colours so it is easy to have your own "types of events" in one view separated. 

fotoshoped example:
![disc-cal_ex](https://user-images.githubusercontent.com/52285099/60268019-bbfa7280-98eb-11e9-8072-47389782c347.png)

**Comment by jonwgeorge** [comment]
Not to but in on a project that I've never contributed to, but...

You can already accomplish this by placing subcategories under your events category. I.E. Events > Example. Whatever you color example and post in there will show up on the main calendar as a separate color.

**Comment by elRicharde** [comment]
Thanks, that´s how we solved this too.

**Comment by angusmcleod** [comment]
@jonwgeorge Thanks!
