### ISSUE TITLE
ics export excludes last day for day-long event

### ISSUE THREAD

**Issue by niccokunzmann** [paviliondev/discourse-events#55]
## Description
To me, it seems, the end of a day-long event is the first second of the new day:

On https://forum.WiLaP.de/t/graffiti-jam-im-freiland-8-bis-11-august/399:
![image](https://user-images.githubusercontent.com/564768/61350540-26a62a80-a868-11e9-9d14-2111624b2a9e.png)
See DTEND: (from https://forum.wilap.de/c/machbar/l/calendar.ics?time_zone=Europe/Berlin)
```
BEGIN:VEVENT
DTSTAMP:20190717T053332Z
UID:45912688-34fd-444b-89b1-69dd6b3dc585
DTSTART;TZID=Europe/Berlin:20190808T000000
DTEND;TZID=Europe/Berlin:20190811T000000
DESCRIPTION:Bitte Außenwände freihalten für Hebebühnen und anderes.
SUMMARY:Graffiti Jam im freiLand 8. bis 11. August
URL:https://forum.WiLaP.de/t/graffiti-jam-im-freiland-8-bis-11-august/399
END:VEVENT
```

Can this be confirmed/contradicted?

## Possible Solutions

It seems, there are several possible solutions:
1. set the end to the second of the following day
2. use a date instead of a datetime, see [DTSTART]

## Implementation

I would advice option 2.
The implementation is here:
https://github.com/angusmcleod/discourse-events/blob/6570a75933b63fdb696cc079c9cd0aa0dcecdf8e/plugin.rb#L492
And the check if this is a day-long event is already here:
https://github.com/angusmcleod/discourse-events/blob/6570a75933b63fdb696cc079c9cd0aa0dcecdf8e/plugin.rb#L486

[DTSTART]: https://www.kanzaki.com/docs/ical/dtstart.html

## Related issues

- https://github.com/niccokunzmann/open-web-calendar/issues/51

**Comment by fzngagan** [comment]
@niccokunzmann . I tried this solution but it has inconsistent results accross platform. In MacOS the issue still persists but in windows, it seems to fix the issue. I'm still working on it to put together a common solution which would work accross all the clients.
