### ISSUE TITLE
No calendar/agenda button showing up in categories

### ISSUE THREAD

**Issue by danielmorlock** [paviliondev/discourse-events#60]
I double checked the setting "events_calendar_enabled" in the category settings but the buttons won't show up. Anything I could help to further investigate this?

**Comment by haveyaseen** [comment]
I'm getting this too, thought it was my fault somehow. The buttons show up as soon as I click on "all categories" in the category dropdown, then on "Categories" and then on the respective category. Probably an Ember related bug.

**Comment by angusmcleod** [comment]
@danielmorlock @haveyaseen Hey guys, there's been a change to Discourse which has affected how content is serialized to the client. This is affected all of our plugins and we're working to fix it. You can follow along here:

https://thepavilion.io/t/add-date-time-button-missing-on-latest-discourse/1533

**Comment by danielmorlock** [comment]
I've fixed the problem here: https://github.com/danielmorlock/discourse-events/commit/c19f9dcea794b012562ccbed5133898e1c9cb424

Unfortunately I'm not that into Discourse plugins. So I'm not sure if this fixes all effects of the upstream change. I think, no :-)

**Comment by haveyaseen** [comment]
Thanks for the heads up @angusmcleod 

> I've fixed the problem here: [danielmorlock@c19f9dc](https://github.com/danielmorlock/discourse-events/commit/c19f9dcea794b012562ccbed5133898e1c9cb424)

Does that really work for you? In my case the `custom_fields` are all `null`: 

![image](https://user-images.githubusercontent.com/6516575/63582438-5cda7680-c599-11e9-85d0-4b058dd92e62.png)

But apparently Pavilion eliminated the root cause, awesome!

**Comment by danielmorlock** [comment]
It works - but `custom_fields` are only not null under some circumstances, so I've added the check against `null` before checking `events_calendar_enabled`. 
As I said, this should be fixed by a maintainer because I'm not that much into this.
