### ISSUE TITLE
Help: Events showing up on the calendar

### ISSUE THREAD

**Issue by slackmoehrle** [paviliondev/discourse-events#70]
I'm making my way through this great plugin. However, I'm having some trouble having events show up on the calendar and also the event icon notated in the topic title. I have checked all the settings for the plugin. I have also rebuild the forums. Any advice?

<img width="1138" alt="Screen Shot 2019-10-17 at 11 35 39" src="https://user-images.githubusercontent.com/7491758/67024576-a6939900-f0d2-11e9-8053-c9581fd6a60e.png">
<img width="769" alt="Screen Shot 2019-10-17 at 11 35 59" src="https://user-images.githubusercontent.com/7491758/67024581-a85d5c80-f0d2-11e9-82ba-961e2a9007e7.png">

**Comment by fzngagan** [comment]
You'll need to enable events for this particular category. Also, the icon you've highlighted is not from our events plugin. It's actually from an official plugin called `discourse-calendar`.

**Comment by slackmoehrle** [comment]
I do:

<img width="517" alt="Screen Shot 2019-10-17 at 11 48 43" src="https://user-images.githubusercontent.com/7491758/67025488-21a97f00-f0d4-11e9-9f0f-8cc248aa5361.png">

**Comment by fzngagan** [comment]
Did you recently update discourse?

**Comment by fzngagan** [comment]
Just try disabling the category setting and save. Then re-enable it.

**Comment by slackmoehrle** [comment]
Thank you, this fixed the issue.
<img width="1122" alt="Screen Shot 2019-10-17 at 19 52 27" src="https://user-images.githubusercontent.com/7491758/67055931-137d5200-f118-11e9-87bc-a612a45558fd.png">
<img width="1132" alt="Screen Shot 2019-10-17 at 19 54 58" src="https://user-images.githubusercontent.com/7491758/67055932-137d5200-f118-11e9-8177-a2c6b7b11c54.png">

**Comment by orlando** [comment]
It worked @fzngagan, thanks!
