### ISSUE TITLE
Allow submitting translations through the Transifex website

### ISSUE THREAD

**Issue by brechtm** [paviliondev/discourse-events#78]
I see you are using Transifex for localization. Would it be possible to enable submitting translations through the Transifex website, as it possible for Discourse itself? Or perhaps this is already possible, but I failed to find the instructions.

**Comment by brechtm** [comment]
Searching https://thepavilion.io, I learned that this already possible, e.g. at https://www.transifex.com/pavilion/discourse-events/. Dutch is not yet in the list of languages, so I requested it.

**Comment by brechtm** [comment]
I went ahead and made a Dutch client localization: #79.

**Comment by fzngagan** [comment]
Thanks for the translation. Closing this one.

**Comment by fzngagan** [comment]
@brechtm 
Were you able to submit the translation via transifex?
