### ISSUE TITLE
Problem with time zones during validation

### ISSUE THREAD

**Issue by poka-IT** [paviliondev/discourse-events#98]
When we are in edit mode of an event, we indicate the correct date as well as the correct time zone.

But when we validate, 1h is added to the indicated time.

How do you know where the problem is coming from?

![image](https://user-images.githubusercontent.com/4574805/139745541-86e0d659-7c18-418e-b3ac-beaae88c9f5c.png)

...

![image](https://user-images.githubusercontent.com/4574805/139745875-525ccd02-3f2a-4410-b10a-448810dbd43e.png)

There is an hour longer than the expected hour for France.

**Comment by bdecotte** [comment]
I've seen something similar with local dates and that has been fixed by https://github.com/discourse/discourse/pull/11408/commits

**Comment by poka-IT** [comment]
I just fixed it by changing this setting:

![image](https://user-images.githubusercontent.com/4574805/139749326-97ea6aff-727f-4308-85bb-446486ebdb7b.png)

The default timezone was bad.
